char ch=' ';
void setup()
{
  Serial.begin(4800);
  pinMode(6,OUTPUT);
  pinMode(7,OUTPUT);
  pinMode(8,OUTPUT);
  pinMode(9,OUTPUT);
  Serial.println("YES!");
}
  /*'F':表示前进
    'B':表示后退
    'R':表示右转
    'L':表示左转
    'S':表示停止
  */
void loop()
 {
  if(Serial.available()>0)
  {
    ch=Serial.read();
  switch(ch)
  {
    case'F':
      digitalWrite(6,HIGH);
      digitalWrite(7,LOW);
      digitalWrite(8,HIGH);
      digitalWrite(9,LOW);
    break;
     case'B':
      digitalWrite(7,HIGH);
      digitalWrite(6,LOW);
      digitalWrite(9,HIGH);
      digitalWrite(8,LOW);
    break;
     case'R':
      digitalWrite(7,HIGH);
      digitalWrite(6,LOW);
      digitalWrite(8,HIGH);
      digitalWrite(9,LOW);
    break;
     case'L':
      digitalWrite(6,HIGH);
      digitalWrite(7,LOW);
      digitalWrite(9,HIGH);
      digitalWrite(8,LOW);
    break;
    case'S':
      digitalWrite(6,LOW);
      digitalWrite(7,LOW);
      digitalWrite(8,LOW);
      digitalWrite(9,LOW);
    break;
    default:
    break;
   }
  }
 }
  